// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl9qH8-_-f2DTuWsRpnvGjkex912aLYfk',
    appId: '1:902357989185:web:c575651f38f5fff22e93c0',
    messagingSenderId: '902357989185',
    projectId: 'villes-1563d',
    authDomain: 'villes-1563d.firebaseapp.com',
    databaseURL: 'https://villes-1563d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'villes-1563d.appspot.com',
    measurementId: 'G-C70L4G14W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsdBP7yqS2_l2ehpyAVHxUdabH4qG5gnA',
    appId: '1:902357989185:android:9b9a38086443cb7e2e93c0',
    messagingSenderId: '902357989185',
    projectId: 'villes-1563d',
    databaseURL: 'https://villes-1563d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'villes-1563d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXogl7VlRmBk-47DWsrGJ1t_jiRDvk1Ps',
    appId: '1:902357989185:ios:97bb6701e7d585e32e93c0',
    messagingSenderId: '902357989185',
    projectId: 'villes-1563d',
    databaseURL: 'https://villes-1563d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'villes-1563d.appspot.com',
    iosClientId: '902357989185-7hddagn9chkicf8eejn90ugl7buj6ns7.apps.googleusercontent.com',
    iosBundleId: 'com.lavenes.ville',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXogl7VlRmBk-47DWsrGJ1t_jiRDvk1Ps',
    appId: '1:902357989185:ios:e334417b2f39a5f02e93c0',
    messagingSenderId: '902357989185',
    projectId: 'villes-1563d',
    databaseURL: 'https://villes-1563d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'villes-1563d.appspot.com',
    iosClientId: '902357989185-kvhgcn3aqv69p8vqrn2fjo2lbg68kvhq.apps.googleusercontent.com',
    iosBundleId: 'com.lavenes.ville.RunnerTests',
  );
}
